dist: trusty
language: go
go_import_path: github.ibm.com/kangh/libnetwork-ovn-plugin
sudo: true

go:
  - 1.8

addons:
  apt:
      packages:
      - libpcap-dev
      - libaspell-dev
      - libhunspell-dev
      - libsystemd-journal-dev

env:
 - DOCKER_OPTS="--cluster-store=consul://127.0.0.1:8500 --cluster-advertise=eth0:2376"

before_install:
 - go get -v -u github.com/chzchzchz/goword
 - go get -v -u honnef.co/go/tools/cmd/gosimple
 - go get -v -u honnef.co/go/tools/cmd/unused
 - go get -v -u honnef.co/go/tools/cmd/staticcheck
 - sudo apt-get update
 - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

script: make test-ci
